apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-params-workflow-
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: this is appel
      - name: username
        value: toto
      - name: backup-message
        value: I'm a backup robot
  templates:
    - name: main
      dag:
        tasks:
        - name: task1
          templateRef:
            name: global-params-template
            template: deliver-message
        - name: task2
          dependencies: [ task1 ]
          templateRef:
            name: print-message-template
            template: print
        - name: task3
          dependencies: [ task1 ]
          templateRef:
            name: print-message-template
            template: backup